#!/bin/bash

TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$TOOLS_ROOT/../" && coverage run --omit "src/antlr/*","test/*,system_test/*" --branch -m nose2 test && coverage report -m
