on: [push, pull_request]

jobs:
  system_tests:
      runs-on: ubuntu-latest
      name: Run unit tests
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build Docker container
          uses: ./
        - name: Run unit tests
          run: "docker run -p 80:8000 --rm shell /comp0010/tools/test"
